pub(crate) mod agent;
pub(crate) mod batch;
pub(crate) mod browser;
pub(crate) mod mock_server;
pub(crate) mod swarm;

use super::*;

pub(super) type ScenarioFn = fn(&mut E2ECtx);

/// Test granularity level.  The default `cargo test --test e2e` run only
/// executes `Basic` scenarios so the suite finishes faster.  Pass
/// `--level=EXTENDED` (or `--level=ALL`) to include longer-running /
/// edge-case tests.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Debug)]
pub(super) enum ScenarioLevel {
    Basic = 1,
    Extended = 2,
}

impl ScenarioLevel {
    pub(super) fn from_arg(value: &str) -> Result<ScenarioLevel, String> {
        match value.trim().to_uppercase().as_str() {
            "BASIC" | "1" => Ok(ScenarioLevel::Basic),
            "EXTENDED" | "2" | "ALL" => Ok(ScenarioLevel::Extended),
            _ => Err(format!(
                "Unknown level '{}'. Valid values: BASIC, EXTENDED (or 1, 2, ALL)",
                value
            )),
        }
    }
}

impl std::fmt::Display for ScenarioLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ScenarioLevel::Basic => write!(f, "BASIC"),
            ScenarioLevel::Extended => write!(f, "EXTENDED"),
        }
    }
}

#[derive(Clone, Copy)]
pub(super) struct ScenarioDef {
    pub(super) name: &'static str,
    pub(super) short_name: &'static str,
    pub(super) requires_browser4: bool,
    pub(super) restart_browser4: bool,
    pub(super) test_count: usize,
    pub(super) test_fn: ScenarioFn,
    /// Optional group tag. Use `--group=<name>` to run only scenarios in that
    /// group.  `None` means the scenario is not assigned to any group and is
    /// only run when no `--group` filter is active.
    pub(super) group: Option<&'static str>,
    /// Test granularity level.  Default `Basic` runs are meant to be fast;
    /// `Extended` scenarios cover edge cases and longer-running tests.
    pub(super) level: ScenarioLevel,
}

impl ScenarioDef {
    pub(super) fn effective_test_count(self) -> usize {
        self.test_count.max(1)
    }

    pub(super) fn is_batch_command_scenario(self) -> bool {
        self.name.contains("_batch_") || self.short_name.contains("batch")
    }

    /// Install / upgrade scenarios download fake runtime bundles and extract
    /// archives — they are disabled by default to keep the default suite fast.
    pub(super) fn is_install_scenario(self) -> bool {
        self.name.contains("_install_") || self.name.contains("_upgrade_")
    }

    /// Returns true when this scenario belongs to `group_name`.
    pub(super) fn in_group(self, group_name: &str) -> bool {
        self.group == Some(group_name)
    }

    /// Returns true when this scenario's level is at or below `max_level`.
    pub(super) fn at_or_below_level(self, max_level: ScenarioLevel) -> bool {
        self.level <= max_level
    }
}

pub(crate) const SCENARIOS: &[ScenarioDef] = &[
    ScenarioDef {
        name: "test_e2e_session_lifecycle",
        short_name: "test_session_lifecycle",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_session_lifecycle,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_newly_opened_session_shows_active",
        short_name: "test_newly_opened_session_shows_active",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_newly_opened_session_shows_active,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_open_recovery_after_browser_kill",
        short_name: "test_open_recovery_after_browser_kill",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_open_recovery_after_browser_kill,
        group: Some("open"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_navigation_and_storage",
        short_name: "test_navigation_and_storage",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_navigation_and_storage,
        group: Some("navigation"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_storage_state_commands",
        short_name: "test_storage_state_commands",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_storage_state_commands,
        group: Some("storage"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_interaction_commands",
        short_name: "test_interaction_commands",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_interaction_commands,
        group: Some("interaction"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_pointer_commands",
        short_name: "test_pointer_commands",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_pointer_commands,
        group: Some("pointer"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_eval_command",
        short_name: "test_eval_command",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_eval_command,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_eval_return_types",
        short_name: "test_eval_return_types",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_eval_return_types,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_eval_css_selector_scoping",
        short_name: "test_eval_css_selector_scoping",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_eval_css_selector_scoping,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_eval_await_command",
        short_name: "test_eval_await_command",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_eval_await_command,
        group: Some("eval"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_agent_run_live_or_missing_llm_key",
        short_name: "test_agent_run_live_or_missing_llm_key",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: agent::test_agent_run_live_or_missing_llm_key,
        group: Some("agent"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_swarm_submission_commands_live",
        short_name: "test_swarm_submission_commands_live",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: swarm::test_swarm_submission_commands_live,
        group: Some("swarm"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_crawl_submission_live",
        short_name: "test_crawl_submission_live",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: swarm::test_crawl_submission_live,
        group: Some("crawl"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_wait_for_state_failure_modes",
        short_name: "test_wait_for_state_failure_modes",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_wait_for_state_failure_modes,
        group: Some("interaction"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_form_controls_and_exports",
        short_name: "test_form_controls_and_exports",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_form_controls_and_exports,
        group: Some("form"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mouse_and_dialog",
        short_name: "test_mouse_and_dialog",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_mouse_and_dialog,
        group: Some("mouse"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mousewheel",
        short_name: "test_mousewheel",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_mousewheel,
        group: Some("mouse"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_tab_commands",
        short_name: "test_tab_commands",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_tab_commands,
        group: Some("tab"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_commands",
        short_name: "test_batch_commands",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_commands,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_form_submission",
        short_name: "test_batch_form_submission",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_form_submission,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_form_submission_from_json_file",
        short_name: "test_batch_form_submission_from_json_file",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_form_submission_from_json_file,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_multi_interaction",
        short_name: "test_batch_multi_interaction",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_multi_interaction,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_error_handling",
        short_name: "test_batch_error_handling",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_error_handling,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_json_edge_cases",
        short_name: "test_batch_json_edge_cases",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: batch::test_batch_json_edge_cases,
        group: Some("batch"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_swarm_session_and_agent_tools",
        short_name: "test_swarm_session_and_agent_tools",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_session_and_agent_tools,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_open_uses_temporary_profile_mode",
        short_name: "test_open_uses_temporary_profile_mode",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_uses_temporary_profile_mode,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_open_with_url_prints_page_state",
        short_name: "test_open_with_url_prints_page_state",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_with_url_prints_page_state,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_open_reuses_existing_active_session",
        short_name: "test_open_reuses_existing_active_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_reuses_existing_active_session,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_named_session_reuses_opened_session",
        short_name: "test_named_session_reuses_opened_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_named_session_reuses_opened_session,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_open_refreshes_inactive_saved_session",
        short_name: "test_open_refreshes_inactive_saved_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_refreshes_inactive_saved_session,
        group: Some("open"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_open_reopens_saved_session_after_human_closed_tab",
        short_name: "test_open_reopens_saved_session_after_human_closed_tab",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_reopens_saved_session_after_human_closed_tab,
        group: Some("open"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_open_navigation_failure_uses_structured_message",
        short_name: "test_open_navigation_failure_uses_structured_message",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_open_navigation_failure_uses_structured_message,
        group: Some("open"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_goto_opens_session_when_missing_or_inactive",
        short_name: "test_goto_opens_session_when_missing_or_inactive",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_goto_opens_session_when_missing_or_inactive,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_batch_reduces_transport_round_trips",
        short_name: "test_batch_reduces_transport_round_trips",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_batch_reduces_transport_round_trips,
        group: Some("batch"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_command",
        short_name: "test_mock_eval_command",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_command,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_css_selector_passthrough",
        short_name: "test_mock_eval_css_selector_passthrough",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_css_selector_passthrough,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_complex_expression",
        short_name: "test_mock_eval_complex_expression",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_complex_expression_falls_to_default,
        group: Some("eval"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_mock_cdp_command",
        short_name: "test_mock_cdp_command",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_cdp_command,
        group: Some("devtools"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_cdp_live_command",
        short_name: "test_cdp_live_command",
        requires_browser4: true,
        restart_browser4: false,
        test_count: 1,
        test_fn: browser::test_cdp_live_command,
        group: Some("devtools"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_standalone_batch",
        short_name: "test_mock_eval_standalone_batch",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_in_standalone_batch,
        group: Some("eval"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_await_command",
        short_name: "test_mock_eval_await_command",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_await_command,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_eval_without_await_omits_flag",
        short_name: "test_mock_eval_without_await_omits_flag",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_eval_without_await_omits_flag,
        group: Some("eval"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_mock_press_command_uses_direct_tool_dispatch",
        short_name: "test_mock_press_command_uses_direct_tool_dispatch",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_press_command_uses_direct_tool_dispatch,
        group: Some("interaction"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_agent_task_commands",
        short_name: "test_agent_task_commands",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_task_commands,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_run_missing_llm_key",
        short_name: "test_agent_run_missing_llm_key",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_run_missing_llm_key,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_status_with_integer_status_code",
        short_name: "test_agent_status_with_integer_status_code",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_status_with_integer_status_code,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_result_not_null_for_failed_task",
        short_name: "test_agent_result_not_null_for_failed_task",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_result_not_null_for_failed_task,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_list_lifecycle_labels",
        short_name: "test_agent_list_lifecycle_labels",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_list_lifecycle_labels,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_list_prunes_terminal_tasks",
        short_name: "test_agent_list_prunes_terminal_tasks",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_list_prunes_terminal_tasks,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_full_lifecycle_with_mock",
        short_name: "test_agent_full_lifecycle_with_mock",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_full_lifecycle_with_mock,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_agent_run_100th_prime",
        short_name: "test_agent_run_100th_prime",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_agent_run_100th_prime,
        group: Some("agent"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_prefixed_flat_forms_are_rejected",
        short_name: "test_prefixed_flat_forms_are_rejected",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_prefixed_flat_forms_are_rejected,
        group: Some("form"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_upload_error_backend_failure",
        short_name: "test_upload_error_backend_failure",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_upload_error_backend_failure,
        group: Some("form"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_submission_commands",
        short_name: "test_swarm_submission_commands",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_submission_commands,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_query_commands",
        short_name: "test_swarm_query_commands",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_query_commands,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_command_help_and_validation",
        short_name: "test_swarm_command_help_and_validation",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_command_help_and_validation,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_status_validation_missing_id",
        short_name: "test_swarm_status_validation_missing_id",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_status_validation_missing_id,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_result_validation_missing_id",
        short_name: "test_swarm_result_validation_missing_id",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_result_validation_missing_id,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_query_validation_errors",
        short_name: "test_swarm_query_validation_errors",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_query_validation_errors,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_list_and_clear",
        short_name: "test_swarm_list_and_clear",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_list_and_clear,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_swarm_close_session",
        short_name: "test_swarm_close_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_swarm_close_session,
        group: Some("swarm"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_submission_commands",
        short_name: "test_crawl_submission_commands",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_submission_commands,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_lifecycle_commands",
        short_name: "test_crawl_lifecycle_commands",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_lifecycle_commands,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_command_help_and_validation",
        short_name: "test_crawl_command_help_and_validation",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_command_help_and_validation,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_with_seed_file",
        short_name: "test_crawl_with_seed_file",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_with_seed_file,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_foreground",
        short_name: "test_crawl_foreground",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_foreground,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_foreground_with_sql",
        short_name: "test_crawl_foreground_with_sql",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_foreground_with_sql,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_with_sql_and_csv_format",
        short_name: "test_crawl_with_sql_and_csv_format",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_with_sql_and_csv_format,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_with_output_file",
        short_name: "test_crawl_with_output_file",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_with_output_file,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_status_missing_id",
        short_name: "test_crawl_status_missing_id",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_status_missing_id,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_result_missing_id",
        short_name: "test_crawl_result_missing_id",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_result_missing_id,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_crawl_cancel_missing_id",
        short_name: "test_crawl_cancel_missing_id",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_crawl_cancel_missing_id,
        group: Some("crawl"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_active_session",
        short_name: "test_close_active_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_active_session,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_no_active_session",
        short_name: "test_close_no_active_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_no_active_session,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_ignores_backend_close_failure",
        short_name: "test_close_ignores_backend_close_failure",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_ignores_backend_close_failure,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_named_session",
        short_name: "test_close_named_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_named_session,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_all_single_server",
        short_name: "test_close_all_single_server",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_all_single_server,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_session_default_promotes_named_to_default",
        short_name: "test_session_default_promotes_named_to_default",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_session_default_promotes_named_to_default,
        group: Some("session-default"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_session_default_warns_overwriting",
        short_name: "test_session_default_warns_overwriting",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_session_default_warns_when_overwriting_default,
        group: Some("session-default"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_session_default_errors_nonexistent",
        short_name: "test_session_default_errors_nonexistent",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_session_default_errors_on_nonexistent,
        group: Some("session-default"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_session_default_updates_timestamp",
        short_name: "test_session_default_updates_timestamp",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_session_default_updates_timestamp,
        group: Some("session-default"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_all_no_active_sessions",
        short_name: "test_close_all_no_active_sessions",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_all_no_active_sessions,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_all_server_unreachable",
        short_name: "test_close_all_server_unreachable",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_all_server_unreachable,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_all_preserves_managed_process_registry",
        short_name: "test_close_all_preserves_managed_process_registry",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_all_preserves_managed_process_registry,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_list_active_session",
        short_name: "test_list_active_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_list_active_session,
        group: Some("list"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_list_stale_session",
        short_name: "test_list_stale_session",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_list_stale_session,
        group: Some("list"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_list_backend_unreachable",
        short_name: "test_list_backend_unreachable",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_list_backend_unreachable,
        group: Some("list"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_list_no_sessions",
        short_name: "test_list_no_sessions",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_list_no_sessions,
        group: Some("list"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_list_multiple_named_sessions",
        short_name: "test_list_multiple_named_sessions",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_list_multiple_named_sessions,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_status_server_up",
        short_name: "test_status_server_up",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_status_server_up,
        group: Some("status"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_status_server_down",
        short_name: "test_status_server_down",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_status_server_down,
        group: Some("status"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_status_server_unreachable",
        short_name: "test_status_server_unreachable",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_status_server_unreachable,
        group: Some("status"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_status_installed_runtime",
        short_name: "test_status_installed_runtime",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_status_installed_runtime,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_status_no_installed_runtime",
        short_name: "test_status_no_installed_runtime",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_status_no_installed_runtime,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_stop_no_running_server",
        short_name: "test_stop_no_running_server",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_stop_no_running_server,
        group: Some("stop"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_stop_clears_state",
        short_name: "test_stop_clears_state",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_stop_clears_state,
        group: Some("stop"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_kill_all_no_running_processes",
        short_name: "test_kill_all_no_running_processes",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_kill_all_no_running_processes,
        group: Some("stop"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_kill_all_clears_state_and_registry",
        short_name: "test_kill_all_clears_state_and_registry",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_kill_all_clears_state_and_registry,
        group: Some("stop"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_close_twice_idempotent",
        short_name: "test_close_twice_idempotent",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_close_twice_idempotent,
        group: Some("close"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_state_isolation_named_vs_default",
        short_name: "test_state_isolation_named_vs_default",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_state_isolation_named_vs_default,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_corrupted_state_file_treated_as_missing",
        short_name: "test_corrupted_state_file_treated_as_missing",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_corrupted_state_file_treated_as_missing,
        group: Some("open"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_install_downloads_and_installs",
        short_name: "test_install_downloads_and_installs",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_downloads_and_installs,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_skips_when_already_installed",
        short_name: "test_install_skips_when_already_installed",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_skips_when_already_installed,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_force_re_downloads",
        short_name: "test_install_force_re_downloads",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_force_re_downloads,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_specific_tag",
        short_name: "test_install_specific_tag",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_specific_tag,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_upgrade_already_latest",
        short_name: "test_upgrade_already_latest",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_upgrade_already_latest,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_upgrade_to_new_version",
        short_name: "test_upgrade_to_new_version",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_upgrade_to_new_version,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_download_failure",
        short_name: "test_install_download_failure",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_download_failure,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_mirror_failover",
        short_name: "test_install_mirror_failover",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_mirror_failover,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_all_mirrors_unreachable",
        short_name: "test_install_all_mirrors_unreachable",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_all_mirrors_unreachable,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_loads_mirrors_json_from_runtime_dir",
        short_name: "test_install_loads_mirrors_json_from_runtime_dir",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_loads_mirrors_json_from_runtime_dir,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_speed_test_selects_fastest_mirror",
        short_name: "test_install_speed_test_selects_fastest_mirror",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_speed_test_selects_fastest_mirror,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_mirror_preference_cache_hit",
        short_name: "test_install_mirror_preference_cache_hit",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_mirror_preference_cache_hit,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_install_speed_test_disabled_env_var",
        short_name: "test_install_speed_test_disabled_env_var",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_install_speed_test_disabled_env_var,
        group: Some("install"),
        level: ScenarioLevel::Extended,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_stdout",
        short_name: "test_snapshot_stdout",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_stdout,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_raw",
        short_name: "test_snapshot_raw",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_raw,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_grep",
        short_name: "test_snapshot_grep",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_grep,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_grep_count",
        short_name: "test_snapshot_grep_count",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_grep_count,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_viewport",
        short_name: "test_snapshot_viewport",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_viewport,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_viewport_range",
        short_name: "test_snapshot_viewport_range",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_viewport_range,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_snapshot_grep_flags",
        short_name: "test_snapshot_grep_flags",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_snapshot_grep_flags,
        group: Some("snapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_capture",
        short_name: "test_htmlsnapshot_capture",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_capture,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_capture_explicit",
        short_name: "test_htmlsnapshot_capture_explicit",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_capture_explicit,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_get_text",
        short_name: "test_htmlsnapshot_get_text",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_get_text,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_get_text_default_selector",
        short_name: "test_htmlsnapshot_get_text_default_selector",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_get_text_default_selector,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_get_attr",
        short_name: "test_htmlsnapshot_get_attr",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_get_attr,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_get_all",
        short_name: "test_htmlsnapshot_get_all",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_get_all,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_get_all_offset_limit",
        short_name: "test_htmlsnapshot_get_all_offset_limit",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_get_all_offset_limit,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_query",
        short_name: "test_htmlsnapshot_query",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_query,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_export",
        short_name: "test_htmlsnapshot_export",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_export,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_summary",
        short_name: "test_htmlsnapshot_summary",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_summary,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_inspect",
        short_name: "test_htmlsnapshot_inspect",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_inspect,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_inspect_with_options",
        short_name: "test_htmlsnapshot_inspect_with_options",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_inspect_with_options,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
    ScenarioDef {
        name: "test_e2e_htmlsnapshot_error_propagation",
        short_name: "test_htmlsnapshot_error_propagation",
        requires_browser4: false,
        restart_browser4: false,
        test_count: 1,
        test_fn: mock_server::test_htmlsnapshot_error_propagation,
        group: Some("htmlsnapshot"),
        level: ScenarioLevel::Basic,
    },
];

pub(super) fn all_scenarios() -> &'static [ScenarioDef] {
    SCENARIOS
}
