package ai.platon.pulsar.agentic.tools.specs

import ai.platon.pulsar.agentic.mcp.McpToolNames
import ai.platon.pulsar.agentic.model.ToolSpec
import ai.platon.pulsar.agentic.tools.ToolErrorCode
import ai.platon.pulsar.common.serialize.json.prettyPulsarObjectMapper

/**
 * Renders the tool registry as the **interface documentation** of the project.
 *
 * The specs are the contract: this generator turns them into artifacts a human
 * or a client can read directly, instead of asking anyone to open the browser
 * library's `WebDriver.kt` KDoc:
 *
 * - a Markdown reference (`docs/mcp-tools.md`) with the signature, argument
 *   table (type, default, meaning), returned value, examples and the MCP tool
 *   name(s) of every tool;
 * - a machine-readable `mcp-tools.json` for the CLI, IDE integrations and
 *   gateways.
 *
 * Both are generated from the same registry the servers advertise, so they
 * cannot describe a tool that does not exist. A test regenerates them and fails
 * on any diff — documentation drift becomes a build error.
 */
object ToolDocGenerator {

    /** One documented tool, ready for serialization. */
    private fun toDoc(spec: ToolSpec, names: List<String>): Map<String, Any?> = linkedMapOf(
        "domain" to spec.domain,
        "method" to spec.method,
        "mcpNames" to names,
        "signature" to spec.expression,
        "description" to spec.description,
        "returnType" to spec.returnType,
        "arguments" to spec.arguments.map { arg ->
            linkedMapOf<String, Any?>(
                "name" to arg.name,
                "type" to arg.type,
                "required" to (arg.defaultValue == null),
                "default" to arg.defaultValue,
                "description" to (arg.description ?: arg.expression),
            )
        },
        "examples" to spec.examples.map { example ->
            linkedMapOf<String, Any?>(
                "title" to example.title,
                "args" to example.args,
                "code" to example.code,
                "notes" to example.notes,
                "expectsError" to example.expectsError,
            )
        },
        "help" to spec.help?.takeIf { it.isNotBlank() && it != spec.description },
    )

    /**
     * Build the documentation payload for [specs].
     *
     * @param canonicalNames maps a `domain.method` key to the MCP tool names it is
     *   advertised under (canonical name plus frontend aliases)
     */
    fun buildDocs(
        specs: Collection<ToolSpec>,
        canonicalNames: Map<String, List<String>> = emptyMap(),
    ): List<Map<String, Any?>> = specs
        .filter { it.domain.isNotBlank() && it.method.isNotBlank() }
        .sortedWith(compareBy({ it.domain }, { it.method }))
        .map { spec ->
            val key = "${spec.domain}.${spec.method}"
            val names = canonicalNames[key] ?: listOf(McpToolNames.toMcpToolName(spec.domain, spec.method))
            toDoc(spec, names)
        }

    /** Machine-readable artifact. */
    fun toJson(docs: List<Map<String, Any?>>): String =
        prettyPulsarObjectMapper().writeValueAsString(linkedMapOf("tools" to docs))

    /** Human-readable artifact. */
    fun toMarkdown(docs: List<Map<String, Any?>>): String = buildString {
        appendLine("# Browser4 MCP tool reference")
        appendLine()
        appendLine("<!-- GENERATED by ToolDocGenerator — do not edit by hand. -->")
        appendLine("<!-- Regenerate: mvn -pl browser4-agentic test -Dtest=ToolDocGeneratorTest -DregenerateToolDocs=true -->")
        appendLine()
        appendLine("${docs.size} tools across ${docs.map { it["domain"] }.distinct().size} domains.")
        appendLine()
        appendErrorCodes(this)

        val byDomain = docs.groupBy { it["domain"] as String }
        for ((domain, tools) in byDomain.entries.sortedBy { it.key }) {
            appendLine("## Domain `$domain`")
            appendLine()
            for (tool in tools) {
                appendTool(this, tool)
            }
        }
    }

    /**
     * The shared failure vocabulary.
     *
     * Every tool reports failures with these codes — in the result text
     * (`ERROR: [CODE] …`), in the MCP result `_meta.errorCode`, and in the
     * private dispatcher's `errorCode` field — so a client can branch on the
     * code instead of matching prose.
     */
    private fun appendErrorCodes(out: StringBuilder) {
        out.appendLine("## Error codes")
        out.appendLine()
        out.appendLine("| Code | Retryable | HTTP | Meaning / what to do |")
        out.appendLine("|---|---|---|---|")
        for (code in ToolErrorCode.entries) {
            out.appendLine("| `${code.wire}` | ${if (code.retryable) "yes" else "no"} | ${code.httpStatus} | ${code.hint} |")
        }
        out.appendLine()
    }

    private fun appendTool(out: StringBuilder, tool: Map<String, Any?>) {
        val names = (tool["mcpNames"] as? List<*>)?.joinToString("`, `") ?: ""
        out.appendLine("### `${names}`")
        out.appendLine()
        out.appendLine("```")
        out.appendLine(tool["signature"])
        out.appendLine("```")
        out.appendLine()
        tool["description"]?.let { out.appendLine(it) }
        out.appendLine()

        @Suppress("UNCHECKED_CAST")
        val args = tool["arguments"] as List<Map<String, Any?>>? ?: emptyList()
        if (args.isNotEmpty()) {
            out.appendLine("| Argument | Type | Required | Default | Meaning |")
            out.appendLine("|---|---|---|---|---|")
            for (arg in args) {
                val default = arg["default"] ?: ""
                val meaning = (arg["description"] as? String).orEmpty().replace("\n", " ").replace("|", "\\|")
                out.appendLine(
                    "| `${arg["name"]}` | ${arg["type"]} | ${if (arg["required"] == true) "yes" else "no"} " +
                        "| $default | $meaning |"
                )
            }
            out.appendLine()
        }

        tool["returnType"]?.let { out.appendLine("Returns: `$it`") }
        out.appendLine()

        @Suppress("UNCHECKED_CAST")
        val examples = tool["examples"] as List<Map<String, Any?>>? ?: emptyList()
        if (examples.isNotEmpty()) {
            out.appendLine("Examples:")
            out.appendLine()
            for (example in examples) {
                val title = example["title"]?.toString()?.takeIf { it.isNotBlank() } ?: "example"
                @Suppress("UNCHECKED_CAST")
                val args = example["args"] as Map<String, String>? ?: emptyMap()
                when {
                    args.isNotEmpty() -> {
                        val json = args.entries.joinToString(", ") { "\"${it.key}\": \"${it.value}\"" }
                        out.appendLine("- $title: `{$json}`")
                    }
                    example["code"] != null -> {
                        out.appendLine("- $title:")
                        out.appendLine()
                        out.appendLine("  ```kotlin")
                        example["code"].toString().lines().forEach { out.appendLine("  $it") }
                        out.appendLine("  ```")
                    }
                }
                example["notes"]?.toString()?.takeIf { it.isNotBlank() }?.let { out.appendLine("  - $it") }
            }
            out.appendLine()
        }

        tool["help"]?.toString()?.takeIf { it.isNotBlank() }?.let {
            out.appendLine("<details><summary>Full documentation</summary>")
            out.appendLine()
            out.appendLine(it)
            out.appendLine()
            out.appendLine("</details>")
            out.appendLine()
        }
    }
}
