#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Scan .issues.md files across draft and review directories, skipping dot-directories,
    and produce a structured summary of all issues found.

.DESCRIPTION
    Recursively scans coworker/tasks/issues/draft and coworker/tasks/issues/review
    for .issues.md files — the structured issue reports generated by the coworker
    evaluation pipeline.

    For each file the worker extracts:
    - Scenario name, source, date, and mode
    - Total issue count
    - Severity breakdown (Critical / High / Medium / Low)
    - Category breakdown (Reliability / UX / Discoverability / Documentation / Product)
    - Review status (pending, accepted, deferred, rejected, fixed)
    - Fix status tracking

    Directories whose names start with '.' are silently skipped.

    Output modes:
    - Default: prints a human-readable summary table to the console
    - CSV (-Csv): writes coworker/tasks/issues/_scan_report.csv
    - JSON (-Json): writes coworker/tasks/issues/_scan_report.json
    - Both (-All): writes both formats

.PARAMETER DraftDir
    Path to the draft issues directory. Defaults to tasks/issues/draft.

.PARAMETER ReviewDir
    Path to the review issues directory. Defaults to tasks/issues/review.

.PARAMETER Csv
    Export results as CSV to tasks/issues/_scan_report.csv.

.PARAMETER Json
    Export results as JSON to tasks/issues/_scan_report.json.

.PARAMETER All
    Export both CSV and JSON reports.

.PARAMETER VerboseOutput
    Print per-file details in addition to the summary.

.PARAMETER MaxFiles
    Limit scan to the first N files (useful for quick checks). 0 = unlimited.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string]$DraftDir = '',

    [string]$ReviewDir = '',

    [switch]$Csv,

    [switch]$Json,

    [switch]$All,

    [switch]$VerboseOutput,

    [int]$MaxFiles = 0
)

$ErrorActionPreference = 'Stop'

# ── Dot-source dependencies ──────────────────────────────────────────────────
$workerDir = Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path (Split-Path -Parent $workerDir) 'config.ps1')

# ── Script-level mutex ──────────────────────────────────────────────────────
$script:__CoworkerLock = New-CoworkerScriptLock -ScriptPath $MyInvocation.MyCommand.Path -SkipIfHeld
if ($null -eq $script:__CoworkerLock) {
    Write-CoworkerLog -Component 'scan-issues' -Level 'WARN' -Message 'Another scan-issues.ps1 instance is already running. Exiting.'
    exit 0
}

$repoRoot = Get-WorkspaceRoot

# ── Directories ──────────────────────────────────────────────────────────────
$issuesRoot = Resolve-TasksPath 'issues'

if ([string]::IsNullOrWhiteSpace($DraftDir)) {
    $DraftDir = Join-Path $issuesRoot 'draft'
}
if ([string]::IsNullOrWhiteSpace($ReviewDir)) {
    $ReviewDir = Join-Path $issuesRoot 'review'
}

# ── Helper: test whether a directory name starts with '.' ────────────────────
function Test-IsDotDirectory {
    param([Parameter(Mandatory)] [string]$DirectoryName)
    return $DirectoryName.StartsWith('.')
}

# ── Helper: recursively collect .issues.md files, skipping dot-directories ──
function Find-IssueFiles {
    param(
        [Parameter(Mandatory)] [string]$BaseDirectory,
        [string]$SourceLabel = 'unknown'
    )

    if (-not (Test-Path $BaseDirectory)) {
        Write-CoworkerLog -Component 'scan-issues' -Level 'WARN' `
            -Message "Directory not found, skipping: $BaseDirectory"
        return @()
    }

    $result = [System.Collections.ArrayList]::new()

    try {
        $stack = [System.Collections.Stack]::new()
        $stack.Push($BaseDirectory)

        while ($stack.Count -gt 0) {
            $currentDir = $stack.Pop()

            # Skip dot-directories (but not the root scan directory itself)
            $dirName = Split-Path -Leaf $currentDir
            if ($currentDir -ne $BaseDirectory -and (Test-IsDotDirectory -DirectoryName $dirName)) {
                Write-CoworkerLog -Component 'scan-issues' -Level 'DEBUG' `
                    -Message "Skipping dot-directory: $currentDir"
                continue
            }

            # Collect .issues.md files in the current directory
            $files = Get-ChildItem -Path $currentDir -File -Filter '*.issues.md' -ErrorAction SilentlyContinue
            foreach ($file in $files) {
                [void]$result.Add(@{
                    FileInfo    = $file
                    SourceLabel = $SourceLabel
                    SourceDir   = $BaseDirectory
                })
            }

            # Push subdirectories onto the stack
            $subdirs = Get-ChildItem -Path $currentDir -Directory -ErrorAction SilentlyContinue |
                Where-Object { -not (Test-IsDotDirectory -DirectoryName $_.Name) }
            foreach ($subdir in $subdirs) {
                $stack.Push($subdir.FullName)
            }
        }
    }
    catch {
        Write-CoworkerLog -Component 'scan-issues' -Level 'ERROR' `
            -Message "Error scanning $BaseDirectory : $_"
    }

    return @($result | Sort-Object { $_.FileInfo.FullName })
}

# ── Issue parsing ────────────────────────────────────────────────────────────
function Parse-IssueFile {
    param(
        [Parameter(Mandatory)] [System.IO.FileInfo]$File,
        [string]$SourceLabel = ''
    )

    $raw = Get-Content -Path $File.FullName -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return $null
    }

    $lines = @($raw -split '\r?\n')

    $record = @{
        FileName       = $File.Name
        FullPath       = $File.FullName
        RelativePath   = $File.FullName.Replace((Resolve-Path (Get-WorkspaceRoot)).Path + '\', '')
        SourceLabel    = $SourceLabel
        ScenarioName   = ''
        SourceFile     = ''
        Date           = ''
        Mode           = ''
        TotalIssues    = 0
        Severity       = @{ Critical = 0; High = 0; Medium = 0; Low = 0 }
        Category       = @{}
        ReviewStatus   = @{
            Pending              = 0
            Accepted             = 0
            AcceptedWithImprovements = 0
            Deferred             = 0
            Wontfix              = 0
            Rejected             = 0
        }
        FixedCount     = 0
        Issues         = [System.Collections.ArrayList]::new()
    }

    $inIssue = $false
    $currentIssue = $null
    $currentReviewSection = $false

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]

        # ── Parse header ──────────────────────────────────────────────────
        if ($line -match '^# Issues:\s*(?<name>.+)$') {
            $record.ScenarioName = $Matches['name'].Trim()
            continue
        }

        if ($line -match '^\> \*\*Source:\*\*\s*`(?<src>[^`]+)`\s*\|\s*\*\*Date:\*\*\s*(?<date>\S+)\s*\|\s*\*\*Mode:\*\*\s*(?<mode>\S+)') {
            $record.SourceFile = $Matches['src'].Trim()
            $record.Date = $Matches['date'].Trim()
            $record.Mode = $Matches['mode'].Trim()
            continue
        }

        # ── Detect issue boundaries ───────────────────────────────────────
        if ($line -match '^### Issue\s+(?<num>\d+):\s*(?<title>.+)$') {
            # Save previous issue if any
            if ($null -ne $currentIssue) {
                [void]$record.Issues.Add($currentIssue)
            }

            $currentIssue = @{
                Number   = [int]$Matches['num']
                Title    = $Matches['title'].Trim()
                Severity = ''
                Category = ''
                Fixed    = $false
                Reviewed = $false
                ReviewDecision = ''
            }
            $inIssue = $true
            $currentReviewSection = $false
            continue
        }

        if (-not $inIssue -or $null -eq $currentIssue) { continue }

        # ── Parse severity ────────────────────────────────────────────────
        if ($line -match '^\*\*Severity:\*\*\s*(?<sev>Critical|High|Medium|Low)') {
            $currentIssue.Severity = $Matches['sev']
            $record.Severity[$currentIssue.Severity]++
            continue
        }

        # ── Parse category ────────────────────────────────────────────────
        if ($line -match '^\*\*Category:\*\*\s*(?<cat>.+)$') {
            $currentIssue.Category = $Matches['cat'].Trim()
            if (-not $record.Category.ContainsKey($currentIssue.Category)) {
                $record.Category[$currentIssue.Category] = 0
            }
            $record.Category[$currentIssue.Category]++
            continue
        }

        # ── Parse review section ──────────────────────────────────────────
        if ($line -match '^\*\*Human Review\*\*') {
            $currentReviewSection = $true
            continue
        }

        if ($currentReviewSection) {
            if ($line -match '- \[[xX]\] \*\*ACCEPT with improvements\*\*') {
                $currentIssue.ReviewDecision = 'ACCEPT with improvements'
                $currentIssue.Reviewed = $true
                $record.ReviewStatus.AcceptedWithImprovements++
                continue
            }
            if ($line -match '- \[[xX]\] \*\*ACCEPT\*\*') {
                $currentIssue.ReviewDecision = 'ACCEPT'
                $currentIssue.Reviewed = $true
                $record.ReviewStatus.Accepted++
                continue
            }
            if ($line -match '- \[[xX]\] \*\*DEFER\*\*') {
                $currentIssue.ReviewDecision = 'DEFER'
                $currentIssue.Reviewed = $true
                $record.ReviewStatus.Deferred++
                continue
            }
            if ($line -match '- \[[xX]\] \*\*WONTFIX\*\*') {
                $currentIssue.ReviewDecision = 'WONTFIX'
                $currentIssue.Reviewed = $true
                $record.ReviewStatus.Wontfix++
                continue
            }
            if ($line -match '- \[[xX]\] \*\*REJECT\*\*') {
                $currentIssue.ReviewDecision = 'REJECT'
                $currentIssue.Reviewed = $true
                $record.ReviewStatus.Rejected++
                continue
            }

            # Detect un-reviewed issues (any unchecked checkbox in human review)
            if ($line -match '- \[ \]') {
                $currentIssue.Reviewed = $false
            }

            # End of review section
            if ($line -match '^---$' -or $line -match '^#{1,3}\s') {
                $currentReviewSection = $false
            }
        }

        # ── Parse fix status ──────────────────────────────────────────────
        if ($line -match '^\*\*Fix status:\*\*\s*(?<status>.+)$') {
            $fixStatus = $Matches['status'].Trim()
            if ($fixStatus -match 'fixed' -or $fixStatus -match 'Fixed') {
                $currentIssue.Fixed = $true
                $record.FixedCount++
            }
        }
    }

    # Save last issue
    if ($null -ne $currentIssue) {
        [void]$record.Issues.Add($currentIssue)
    }

    # Count pending reviews
    $reviewedCount = $record.ReviewStatus.Accepted + $record.ReviewStatus.AcceptedWithImprovements +
                     $record.ReviewStatus.Deferred + $record.ReviewStatus.Wontfix +
                     $record.ReviewStatus.Rejected
    $record.ReviewStatus.Pending = $record.Issues.Count - $reviewedCount
    if ($record.ReviewStatus.Pending -lt 0) { $record.ReviewStatus.Pending = 0 }

    $record.TotalIssues = $record.Issues.Count

    return $record
}

# ── Summary aggregation ─────────────────────────────────────────────────────
function New-ScanSummary {
    param(
        [Parameter(Mandatory)] [array]$Records
    )

    if ($Records.Count -eq 0) {
        return @{
            TotalFiles         = 0
            TotalIssues        = 0
            TotalFixed         = 0
            TotalReviewed      = 0
            TotalPending       = 0
            Severity           = @{ Critical = 0; High = 0; Medium = 0; Low = 0 }
            Category           = @{}
            ReviewStatus       = @{
                Accepted                 = 0
                AcceptedWithImprovements = 0
                Deferred                 = 0
                Wontfix                  = 0
                Rejected                 = 0
                Pending                  = 0
            }
            DraftCount         = 0
            ReviewCount        = 0
        }
    }

    $summary = @{
        TotalFiles    = $Records.Count
        TotalIssues   = 0
        TotalFixed    = 0
        TotalReviewed = 0
        TotalPending  = 0
        Severity      = @{ Critical = 0; High = 0; Medium = 0; Low = 0 }
        Category      = @{}
        ReviewStatus  = @{
            Accepted                 = 0
            AcceptedWithImprovements = 0
            Deferred                 = 0
            Wontfix                  = 0
            Rejected                 = 0
            Pending                  = 0
        }
        DraftCount    = 0
        ReviewCount   = 0
    }

    foreach ($r in $Records) {
        $summary.TotalIssues += $r.TotalIssues
        $summary.TotalFixed  += $r.FixedCount

        foreach ($key in @('Critical', 'High', 'Medium', 'Low')) {
            $summary.Severity[$key] += $r.Severity[$key]
        }

        foreach ($cat in $r.Category.Keys) {
            if (-not $summary.Category.ContainsKey($cat)) {
                $summary.Category[$cat] = 0
            }
            $summary.Category[$cat] += $r.Category[$cat]
        }

        foreach ($key in @('Accepted', 'AcceptedWithImprovements', 'Deferred', 'Wontfix', 'Rejected', 'Pending')) {
            $summary.ReviewStatus[$key] += $r.ReviewStatus[$key]
        }

        if ($r.SourceLabel -eq 'draft') { $summary.DraftCount++ }
        else { $summary.ReviewCount++ }
    }

    $summary.TotalReviewed = $summary.ReviewStatus.Accepted + $summary.ReviewStatus.AcceptedWithImprovements +
                             $summary.ReviewStatus.Deferred + $summary.ReviewStatus.Wontfix +
                             $summary.ReviewStatus.Rejected
    $summary.TotalPending = $summary.TotalIssues - $summary.TotalReviewed

    return $summary
}

# ── Output formatters ────────────────────────────────────────────────────────
function Write-SummaryToConsole {
    param(
        [Parameter(Mandatory)] $Summary,
        [Parameter(Mandatory)] [array]$Records,
        [switch]$ShowDetails
    )

    $sep = "`n$( '-' * 72 )"

    Write-Host $sep
    Write-Host '  ISSUE SCAN REPORT' -ForegroundColor Cyan
    Write-Host ('─' * 72)
    Write-Host ('  Generated : ' + (Get-CoworkerTimestamp))
    Write-Host ('  Files     : ' + $Summary.TotalFiles + ' .issues.md files')
    Write-Host ('  Draft     : ' + $Summary.DraftCount + ' file(s)')
    Write-Host ('  Review    : ' + $Summary.ReviewCount + ' file(s)')
    Write-Host ('  Issues    : ' + $Summary.TotalIssues + ' total')
    Write-Host ''

    # Severity breakdown
    Write-Host '  Severity Breakdown:' -ForegroundColor Yellow
    $sevTotal = $Summary.TotalIssues
    foreach ($sev in @('Critical', 'High', 'Medium', 'Low')) {
        $count = $Summary.Severity[$sev]
        if ($count -gt 0) {
            $pct = if ($sevTotal -gt 0) { [Math]::Round(100 * $count / $sevTotal, 1) } else { 0 }
            $color = switch ($sev) {
                'Critical' { 'Red' }
                'High'     { 'Magenta' }
                'Medium'   { 'Yellow' }
                default    { 'Gray' }
            }
            Write-Host ('    {0,-10} : {1,4}  ({2,5}%)' -f $sev, $count, $pct) -ForegroundColor $color
        }
    }

    Write-Host ''

    # Category breakdown
    if ($Summary.Category.Keys.Count -gt 0) {
        Write-Host '  Category Breakdown:' -ForegroundColor Yellow
        foreach ($cat in ($Summary.Category.Keys | Sort-Object { -$Summary.Category[$_] })) {
            $count = $Summary.Category[$cat]
            $pct = if ($sevTotal -gt 0) { [Math]::Round(100 * $count / $sevTotal, 1) } else { 0 }
            Write-Host ('    {0,-25} : {1,4}  ({2,5}%)' -f $cat, $count, $pct)
        }
        Write-Host ''
    }

    # Review status
    Write-Host '  Review Status:' -ForegroundColor Yellow
    Write-Host ('    {0,-25} : {1,4}' -f 'ACCEPT', $Summary.ReviewStatus.Accepted) -ForegroundColor Green
    Write-Host ('    {0,-25} : {1,4}' -f 'ACCEPT with improvements', $Summary.ReviewStatus.AcceptedWithImprovements) -ForegroundColor Green
    Write-Host ('    {0,-25} : {1,4}' -f 'DEFER', $Summary.ReviewStatus.Deferred) -ForegroundColor DarkYellow
    Write-Host ('    {0,-25} : {1,4}' -f 'WONTFIX', $Summary.ReviewStatus.Wontfix) -ForegroundColor Gray
    Write-Host ('    {0,-25} : {1,4}' -f 'REJECT', $Summary.ReviewStatus.Rejected) -ForegroundColor Red
    Write-Host ('    {0,-25} : {1,4}' -f 'PENDING REVIEW', $Summary.ReviewStatus.Pending) -ForegroundColor Cyan
    Write-Host ('    {0,-25} : {1,4}' -f '-- Total Reviewed', $Summary.TotalReviewed)
    Write-Host ''

    # Fix status
    if ($Summary.TotalFixed -gt 0) {
        Write-Host ('  Fixes applied : ' + $Summary.TotalFixed + ' issue(s) marked fixed') -ForegroundColor Green
        Write-Host ''
    }

    # Per-file details
    if ($ShowDetails) {
        Write-Host ('─' * 72)
        Write-Host '  Per-File Details' -ForegroundColor Cyan
        Write-Host ('─' * 72)

        foreach ($r in $Records) {
            $label = if ($r.SourceLabel -eq 'draft') { 'DRAFT' } else { 'REVIEW' }
            $labelColor = if ($label -eq 'DRAFT') { 'Yellow' } else { 'Cyan' }
            $pendingTag = if ($r.ReviewStatus.Pending -gt 0) { " [$($r.ReviewStatus.Pending) pending]" } else { '' }

            Write-Host ''
            Write-Host ('  [{0}] {1}{2}' -f $label, $r.ScenarioName, $pendingTag) -ForegroundColor $labelColor
            Write-Host ('    File    : ' + $r.FileName)
            Write-Host ('    Date    : ' + $r.Date + '  |  Mode: ' + $r.Mode)
            Write-Host ('    Issues  : ' + $r.TotalIssues)
            Write-Host ('    Severity: C:' + $r.Severity.Critical + ' H:' + $r.Severity.High +
                        ' M:' + $r.Severity.Medium + ' L:' + $r.Severity.Low)
            Write-Host ('    Review  : A:' + $r.ReviewStatus.Accepted +
                        ' A+i:' + $r.ReviewStatus.AcceptedWithImprovements +
                        ' D:' + $r.ReviewStatus.Deferred +
                        ' W:' + $r.ReviewStatus.Wontfix +
                        ' R:' + $r.ReviewStatus.Rejected +
                        ' P:' + $r.ReviewStatus.Pending)

            if ($r.FixedCount -gt 0) {
                Write-Host ('    Fixed   : ' + $r.FixedCount) -ForegroundColor Green
            }

            # List individual issues
            foreach ($issue in $r.Issues) {
                $sevColor = switch ($issue.Severity) {
                    'Critical' { 'Red' }
                    'High'     { 'Magenta' }
                    'Medium'   { 'Yellow' }
                    default    { 'Gray' }
                }

                $statusMarkers = [System.Text.StringBuilder]::new()
                if ($issue.Reviewed) {
                    $decision = switch ($issue.ReviewDecision) {
                        'ACCEPT'                    { '✓' }
                        'ACCEPT with improvements'  { '✓+' }
                        'DEFER'                     { '⏳' }
                        'WONTFIX'                   { '✗W' }
                        'REJECT'                    { '✗R' }
                        default                     { '?' }
                    }
                    [void]$statusMarkers.Append($decision)
                }
                else {
                    [void]$statusMarkers.Append('○')
                }
                if ($issue.Fixed) {
                    [void]$statusMarkers.Append('🔧')
                }

                Write-Host ('      [{0}] #{1}: {2} ({3})' -f $statusMarkers.ToString(), $issue.Number,
                    $issue.Title, $issue.Severity) -ForegroundColor $sevColor
            }
        }
    }

    Write-Host $sep
}

function Export-ScanToCsv {
    param(
        [Parameter(Mandatory)] [array]$Records,
        [Parameter(Mandatory)] [string]$OutputPath
    )

    $csvRows = [System.Collections.ArrayList]::new()

    foreach ($r in $Records) {
        foreach ($issue in $r.Issues) {
            [void]$csvRows.Add([PSCustomObject]@{
                Source          = $r.SourceLabel
                FileName        = $r.FileName
                ScenarioName    = $r.ScenarioName
                ScenarioDate    = $r.Date
                ScenarioMode    = $r.Mode
                IssueNumber     = $issue.Number
                IssueTitle      = $issue.Title
                Severity        = $issue.Severity
                Category        = $issue.Category
                Reviewed        = $issue.Reviewed
                ReviewDecision  = $issue.ReviewDecision
                Fixed           = $issue.Fixed
            })
        }
    }

    if ($PSCmdlet.ShouldProcess($OutputPath, 'Write CSV report')) {
        $csvRows | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
    }
    Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
        -Message "CSV report written: $OutputPath ($($csvRows.Count) rows)"
}

function Export-ScanToJson {
    param(
        [Parameter(Mandatory)] $Summary,
        [Parameter(Mandatory)] [array]$Records,
        [Parameter(Mandatory)] [string]$OutputPath
    )

    # Convert records from hashtable arrays to a serializable form
    $serializableRecords = @()
    foreach ($r in $Records) {
        $serializableRecords += @{
            FileName       = $r.FileName
            RelativePath   = $r.RelativePath
            SourceLabel    = $r.SourceLabel
            ScenarioName   = $r.ScenarioName
            SourceFile     = $r.SourceFile
            Date           = $r.Date
            Mode           = $r.Mode
            TotalIssues    = $r.TotalIssues
            Severity       = $r.Severity
            Category       = $r.Category
            ReviewStatus   = $r.ReviewStatus
            FixedCount     = $r.FixedCount
            Issues         = @($r.Issues | ForEach-Object { $_ })
        }
    }

    $report = @{
        GeneratedAt    = Get-CoworkerTimestamp
        Summary        = $Summary
        Files          = $serializableRecords
    }

    if ($PSCmdlet.ShouldProcess($OutputPath, 'Write JSON report')) {
        $report | ConvertTo-Json -Depth 5 | Set-Content -Path $OutputPath -Encoding UTF8
    }
    Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
        -Message "JSON report written: $OutputPath"
}

# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' -Message 'Starting .issues.md scan'

# ── Discover files ───────────────────────────────────────────────────────────
$draftFiles  = Find-IssueFiles -BaseDirectory $DraftDir -SourceLabel 'draft'
$reviewFiles = Find-IssueFiles -BaseDirectory $ReviewDir -SourceLabel 'review'
$allFiles    = $draftFiles + $reviewFiles

if ($MaxFiles -gt 0 -and $allFiles.Count -gt $MaxFiles) {
    $allFiles = @($allFiles | Select-Object -First $MaxFiles)
    Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
        -Message "Limited to first $MaxFiles file(s)"
}

if ($allFiles.Count -eq 0) {
    Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
        -Message 'No .issues.md files found in draft or review directories.'
    Write-Host 'No .issues.md files found.' -ForegroundColor Yellow
    Remove-CoworkerScriptLock -Lock $script:__CoworkerLock
    exit 0
}

Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
    -Message "Found $($draftFiles.Count) draft + $($reviewFiles.Count) review = $($allFiles.Count) .issues.md file(s)"

# ── Parse ────────────────────────────────────────────────────────────────────
$records = [System.Collections.ArrayList]::new()
$parseFailures = 0

foreach ($entry in $allFiles) {
    try {
        $record = Parse-IssueFile -File $entry.FileInfo -SourceLabel $entry.SourceLabel
        if ($null -ne $record) {
            [void]$records.Add($record)
        }
        else {
            $parseFailures++
            Write-CoworkerLog -Component 'scan-issues' -Level 'WARN' `
                -Message "Failed to parse (empty or malformed): $($entry.FileInfo.Name)"
        }
    }
    catch {
        $parseFailures++
        Write-CoworkerLog -Component 'scan-issues' -Level 'ERROR' `
            -Message "Parse error for $($entry.FileInfo.Name) : $_"
    }
}

# ── Summarize ────────────────────────────────────────────────────────────────
$summary = New-ScanSummary -Records @($records)

# ── Output ───────────────────────────────────────────────────────────────────
Write-SummaryToConsole -Summary $summary -Records @($records) -ShowDetails:$VerboseOutput

if ($Csv -or $All) {
    $csvPath = Join-Path $issuesRoot '_scan_report.csv'
    Export-ScanToCsv -Records @($records) -OutputPath $csvPath
}

if ($Json -or $All) {
    $jsonPath = Join-Path $issuesRoot '_scan_report.json'
    Export-ScanToJson -Summary $summary -Records @($records) -OutputPath $jsonPath
}

if ($parseFailures -gt 0) {
    Write-CoworkerLog -Component 'scan-issues' -Level 'WARN' `
        -Message "Scan complete with $parseFailures parse failure(s) out of $($allFiles.Count) file(s)"
}
else {
    Write-CoworkerLog -Component 'scan-issues' -Level 'INFO' `
        -Message "Scan complete: $($summary.TotalFiles) files, $($summary.TotalIssues) issues"
}

Remove-CoworkerScriptLock -Lock $script:__CoworkerLock
exit 0
