spring.main.allow-bean-definition-overriding=true

server.port=8182
server.servlet.context-path=/

spring.jackson.serialization.INDENT_OUTPUT=true

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.packages-to-scan=ai.platon.pulsar.rest.api.webdriver
