package ai.platon.pulsar.skeleton.workflow.parse.html

/**
 * Built-in page summary algorithm: the deterministic Web Page Summary Index
 * (WPSI) YAML generated by [PageSummaryIndexService].
 *
 * Registered by default in [PageSummaryAlgorithmRegistry] under [ID]. The
 * actual algorithm remains in [PageSummaryIndexService] because parts of it
 * (`detectLinkGroups`, `SummaryLinkGroup`, `ViBox`) are also shared by the
 * `htmlsnapshot inspect` and `htmlsnapshot capture` commands; this object is
 * the thin adapter that exposes it through the [PageSummaryAlgorithm] SPI.
 */
object WpsiPageSummaryAlgorithm : PageSummaryAlgorithm {

    /** Stable id used by `--algorithm wpsi`. */
    const val ID = "wpsi"

    override val id: String = ID
    override val displayName: String = "Web Page Summary Index (WPSI)"
    override val description: String =
        "Deterministic compressed YAML summary: page type, landmarks, scored key content " +
            "nodes with selector hints, repeated lists/tables, detected link groups and " +
            "statistics. Typically 0.1%-1% of the original HTML size. No LLM is involved."
    override val builtin: Boolean = true

    override fun generate(input: PageSummaryInput): String =
        PageSummaryIndexService.generate(input.document, input.pageUrl, input.title)
}
